kind: pipeline
name: integration-tests-master

clone:
  depth: 1

steps:
  - name: integration-tests-master
    image: ghcr.io/nextcloud/continuous-integration-user_saml_shibboleth-php8.0:latest
    environment:
      CORE_BRANCH: master
    commands:
      - /start.sh
      - /wait-for-services.sh
      - rm -rf /var/www/html
      - cd /var/www/
      - git clone --depth 1 -b $CORE_BRANCH https://github.com/nextcloud/server html
      - cd /var/www/html && git submodule update --init
      # use local clone
      - cp -r /drone/src /var/www/html/apps/user_saml
      - cd /opt/ && curl -sS https://getcomposer.org/installer | php
      - php /opt/composer.phar install --no-dev -d /var/www/html/apps/user_saml/3rdparty/
      - php /var/www/html/occ maintenance:install --database sqlite --admin-pass password
      - php /var/www/html/occ app:enable user_saml
      - chown -R apache:apache /var/www/html/
      - cd /var/www/html/apps/user_saml/tests/integration && php /opt/composer.phar composer install && vendor/bin/behat

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

type: docker

---
kind: pipeline
name: integration-tests-stable23

clone:
  depth: 1

steps:
  - name: integration-tests-stable23
    image: ghcr.io/nextcloud/continuous-integration-user_saml_shibboleth-php7.3:latest
    environment:
      CORE_BRANCH: stable23
    commands:
      - /start.sh &
      - /wait-for-services.sh
      - rm -rf /var/www/html
      - cd /var/www/
      - git clone --depth 1 -b $CORE_BRANCH https://github.com/nextcloud/server html
      - cd /var/www/html && git submodule update --init
      # use local clone
      - cp -r /drone/src /var/www/html/apps/user_saml
      - scl enable rh-php73 "bash -c 'cd /opt/ && curl -sS https://getcomposer.org/installer | php'"
      - scl enable rh-php73 "bash -c 'cd /var/www/html/apps/user_saml/ && php /opt/composer.phar install --no-dev'"
      - scl enable rh-php73 "bash -c 'php /var/www/html/occ maintenance:install --database sqlite --admin-pass password; php /var/www/html/occ app:enable user_saml'"
      - chown -R apache:apache /var/www/html/
      - scl enable rh-php73  "bash -c 'cd /var/www/html/apps/user_saml/tests/integration && php /opt/composer.phar install && vendor/bin/behat'"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

type: docker

---
kind: pipeline
name: integration-tests-stable22

clone:
  depth: 1

steps:
  - name: integration-tests-stable22
    image: ghcr.io/nextcloud/continuous-integration-user_saml_shibboleth-php7.3:latest
    environment:
      CORE_BRANCH: stable22
    commands:
      - /start.sh &
      - /wait-for-services.sh
      - rm -rf /var/www/html
      - cd /var/www/
      - git clone --depth 1 -b $CORE_BRANCH https://github.com/nextcloud/server html
      - cd /var/www/html && git submodule update --init
      # use local clone
      - scl enable rh-php73 "bash -c 'cd /opt/ && curl -sS https://getcomposer.org/installer | php'"
      - scl enable rh-php73 "bash -c 'php /opt/composer.phar install --no-dev -d /var/www/html/apps/user_saml/3rdparty"
      - scl enable rh-php73 "bash -c 'php /var/www/html/occ maintenance:install --database sqlite --admin-pass password; php /var/www/html/occ app:enable user_saml'"
      - chown -R apache:apache /var/www/html/
      - scl enable rh-php73  "bash -c 'cd /var/www/html/apps/user_saml/tests/integration && php /opt/composer.phar install && vendor/bin/behat'"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

type: docker

---
kind: pipeline
name: integration-tests-stable21

clone:
  depth: 1

steps:
  - name: integration-tests-stable21
    image: ghcr.io/nextcloud/continuous-integration-user_saml_shibboleth-php7.3:latest
    environment:
      CORE_BRANCH: stable21
    commands:
      - /start.sh &
      - /wait-for-services.sh
      - rm -rf /var/www/html
      - cd /var/www/
      - git clone --depth 1 -b $CORE_BRANCH https://github.com/nextcloud/server html
      - cd /var/www/html && git submodule update --init
      # use local clone
      - scl enable rh-php73 "bash -c 'cd /opt/ && curl -sS https://getcomposer.org/installer | php'"
      - scl enable rh-php73 "bash -c 'php /opt/composer.phar install --no-dev -d /var/www/html/apps/user_saml/3rdparty"
      - scl enable rh-php73 "bash -c 'php /var/www/html/occ maintenance:install --database sqlite --admin-pass password; php /var/www/html/occ app:enable user_saml'"
      - chown -R apache:apache /var/www/html/
      - scl enable rh-php73  "bash -c 'cd /var/www/html/apps/user_saml/tests/integration && php /opt/composer.phar install &&  vendor/bin/behat'"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

type: docker
