
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

tasks:
  - name: Nextcloud Server
    init: |
      # Install Docker 20 (Gitpod is still on version 19 by default)
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo apt-key fingerprint 0EBFCD88
      sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
      sudo apt-get install docker-ce-cli
    command: |
      git config core.fileMode false
      chmod -R 777 .
      cd gitpod
      export SIMPLESAML_URL=$(gp url 8082)/simplesaml
      export NEXTCLOUD_URL=$(gp url 8080)
      
      curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
      chmod +x envsubst
      sudo mv envsubst /usr/local/bin

      envsubst < mariadb/prepopulate.sql.template > mariadb/prepopulate.sql
      envsubst < simplesamlphp/var-simplesamlphp/metadata/saml20-sp-remote.php.template > simplesamlphp/var-simplesamlphp/metadata/saml20-sp-remote.php
      docker-compose up

  - name: Terminal
    command: clear

ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
  - port: 8081
    visibility: private
    onOpen: ignore
  - port: 8082
    visibility: private
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - felixfbecker.php-debug
